const Clothing = [
  {
    id: 1,
    name: 'Nike Shoes',
    image: require('../assets/Clothing/man.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    description: 'The best shoes to buy ever man',
    category: 'Foot Wear',
    like: false,
  },

  {
    id: 1,
    name: 'Top tree color Nike',
    image: require('../assets/Clothing/TopTricolorNike.jpg'),
    price: 300,
    rating: [1, 3, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'Top',
    like: true,
  },
  {
    id: 1,
    name: 'Pants Blue',
    image: require('../assets/Clothing/man.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'pants',
    category: 'Foot wear',
  },
  {
    id: 1,
    name: 'Tree color nike',
    image: require('../assets/Clothing/triColorNike.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'watch',
  },
  {
    id: 1,
    name: 'Black and Yellow',
    image: require('../assets/Clothing/BlackYellowNike.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'pants',
  },
  {
    id: 1,
    name: 'Red Nike',
    image: require('../assets/Clothing/redNike.jpeg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'Foot Wear',
  },

  {
    id: 1,
    name: 'White T-shirt',
    image: require('../assets/Clothing/shirt.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'pants',
  },
  {
    id: 1,
    name: 'NikeTenis',
    image: require('../assets/john.jpg'),
    price: 300,
    rating: [1, 3, 4, 5],
    discount: 30,
    description: 'The best shoes to buy ever man',
    category: 'Foot Wear',
  },
]
export default Clothing
